"""The migration is the schema: it must build §6 and unbuild it, cleanly.

Every test here runs against its own temp database — never the dev database (the
`conftest` module pins `DATABASE_URL` to a scratch file before `app.config` is
imported, and each test overrides it again for the alembic run).

`sqlite3` (the CLI) is not installed in this environment; inspection goes
through SQLAlchemy or the stdlib module.
"""

from __future__ import annotations

from pathlib import Path

from alembic.util.exc import CommandError
from sqlalchemy import inspect

from alembic import command
from tests.conftest import (
    alembic_config,
    database_url,
    make_engine,
    run_downgrade,
    run_upgrade,
    sqlite_url,
)
from tests.test_schema_tables import SPEC_TABLES


def _table_names(path: Path) -> set[str]:
    engine = make_engine(path)
    try:
        return set(inspect(engine).get_table_names())
    finally:
        engine.dispose()


def test_upgrade_head_creates_every_section6_table(tmp_path: Path) -> None:
    path = tmp_path / "upgrade.db"
    run_upgrade(sqlite_url(path))
    assert set(SPEC_TABLES) <= _table_names(path)


def test_downgrade_base_removes_every_section6_table(tmp_path: Path) -> None:
    """A downgrade that leaves tables behind makes the next upgrade fail — and
    hides drift. Only alembic's own bookkeeping may survive."""
    path = tmp_path / "downgrade.db"
    run_upgrade(sqlite_url(path))
    run_downgrade(sqlite_url(path))

    remaining = _table_names(path)
    assert remaining & set(SPEC_TABLES) == set()
    assert remaining <= {"alembic_version"}


def test_upgrade_downgrade_upgrade_is_repeatable(tmp_path: Path) -> None:
    """Proves the downgrade really is the upgrade's inverse: if it left an index
    or a table behind, the second upgrade would raise."""
    path = tmp_path / "cycle.db"
    url = sqlite_url(path)
    run_upgrade(url)
    run_downgrade(url)
    run_upgrade(url)
    assert set(SPEC_TABLES) <= _table_names(path)


def test_alembic_check_reports_no_drift_between_models_and_migration(tmp_path: Path) -> None:
    """`alembic check` autogenerates against the migrated database and raises if
    the models would produce any further DDL. This is what lets the other schema
    tests interrogate the migration alone and still cover `app/models.py`.
    """
    path = tmp_path / "check.db"
    url = sqlite_url(path)
    run_upgrade(url)

    with database_url(url):
        # Raises AutogenerateDiffsDetected (a CommandError) on drift; the diff is
        # in the message, so let it surface rather than asserting a bool.
        command.check(alembic_config(url))


def test_alembic_check_fails_when_the_database_lags_the_models(tmp_path: Path) -> None:
    """The drift check above would be worthless if `command.check` never failed.
    An empty database is maximal drift — it must be detected."""
    path = tmp_path / "empty.db"
    url = sqlite_url(path)
    make_engine(path).dispose()

    with database_url(url):
        try:
            command.check(alembic_config(url))
        except CommandError:
            return
    raise AssertionError("alembic check passed against an empty database")


def test_migration_head_is_singular(tmp_path: Path) -> None:
    """Two heads mean an ambiguous `upgrade head`; catch the branch at the gate."""
    from alembic.script import ScriptDirectory

    script = ScriptDirectory.from_config(alembic_config(sqlite_url(tmp_path / "x.db")))
    assert len(script.get_heads()) == 1
