"""assignments weekday-only unique index (H5 weekend two-spiaggini)

Revision ID: 19714fc7d4f1
Revises: 29c1599bed92
Create Date: 2026-07-17 01:41:54.148684

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "19714fc7d4f1"
down_revision: str | Sequence[str] | None = "29c1599bed92"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("assignments", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_assignments_week_id_day_slot_role"), type_="unique")
        batch_op.create_index(
            "uq_assignments_weekday_slot",
            ["week_id", "day", "slot", "role"],
            unique=True,
            sqlite_where=sa.text("day IN ('mon', 'tue', 'wed', 'thu', 'fri')"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("assignments", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_assignments_weekday_slot",
            sqlite_where=sa.text("day IN ('mon', 'tue', 'wed', 'thu', 'fri')"),
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_assignments_week_id_day_slot_role"), ["week_id", "day", "slot", "role"]
        )

    # ### end Alembic commands ###
